[project]
name = "amazon-neptune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.0",
    "strands-agents>=0.1.6",
    "strands-agents-tools>=0.1.4",
]
